# Use the official Python base image
FROM python:alpine3.17

# Set the working directory
WORKDIR .

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pymongo==4.3.3

# Copy the source code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 5001

# Start the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]