version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'

  meals:
    build: ./meals
    restart: always
    ports:
      - '5001:8000'
    depends_on:
      - mongo
    environment:
      - FLASK_DEBUG=true

  diets:
    build: ./diets
    restart: always
    ports:
      - '5002:8000'
    # expose:
    #   - 5002
    depends_on:
      - mongo
    environment:
      - FLASK_DEBUG=true

  reverse:
    build: ./reverse
    restart: always
    ports:
      - '80:80'
    depends_on:
      - meals
      - diets
    volumes:
      - ./reverse/nginx.conf:/etc/nginx/conf.d/default.conf