# Use the official Python base image
FROM python:alpine3.17

# Set the working directory
WORKDIR ./app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Start the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]